server:
  port: 9000
spring: 
  session: 
    store-type: jdbc
    jdbc: 
      initialize-schema: always
      timeout: 
        seconds: 600
  h2:
    console: 
      enabled: true
  datasource: 
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/tech_news?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: ${DB_USER}
    password: ${DB_PASS}
  application: 
    name: technews_api
  jpa: 
    hibernate: 
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true